# Generated by Django 2.2 on 2019-04-17 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.IntegerField(blank=True, choices=[(0, 'CreateEvent'), (1, 'WatchEvent'), (2, 'ForkEvent'), (3, 'PublicEvent')], null=True),
        ),
    ]
