# Generated by Django 2.2 on 2019-04-17 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20190417_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
