# Generated by Django 2.2 on 2019-04-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_auto_20190417_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='main_language',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
